name: Send submodule updates to parent repo

on:
  push:
    branches: 
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Load secret
        id: load-secret
        uses: 1password/load-secrets-action@v1
        env:
          GITHUB_NOTEPAD_RAW_TOKEN: op://github-secrets/notepad-raw/credential

      - name: Checkout notepad repo
        uses: actions/checkout@v2
        with: 
          repository: lambainsaan/notepad
          token: ${{ steps.load-secret.outputs.GITHUB_NOTEPAD_RAW_TOKEN }}
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
